---
- job:
    name: test-linters
    parent: tox-linters
    nodeset:
      nodes:
        - name: test-node
          label: ubuntu-jammy

- project:
    check:
      jobs:
        - test-linters
    gate:
      jobs:
        - test-linters
