---
- secret:
    name: osfrickler_docs_creds
    data:
      rclone: !encrypted/pkcs1-oaep
        - WxFgch9r/gRd194SZ0bPy8UfQlpSPCsDG0X8BdEXlqTEE1L/KqjH5QuMBudNKuIjb3B5D
          LpzVXBlM7D7mggyu0AbWpnnumUDLQGeL7CeNCZwbIi/bZeqDjUUNsc9AqbergYnL4Lw+n
          5j/z5JXyfZQ1EC7/+s5ezsjJTQ59fgoSZNKIC1Fh8plTPnPN68J1SJXwrd9/BNShe0ElZ
          1WioqHYbneraN4Qv1Gx2kPEwYMkPmySFR+mgeBwJtjohaHGsjbF1W3ID3CO4K5xSZHH/S
          NSHP6cye58zZXUiLu1WbJPxu3225jHBtu9spsyiC/YekqRoj/ad6CsCvnVlGPK1Vjrcaf
          mmQfaEcLoyz1GlQFEl4M0osHJYb2m9BzUuiodjAA64QtkJIkvsAl4ryUbhaaKLi439e8A
          M+99HLkfrddZByeRzKZwhFh03XHb+opV4GEGLOa5Ah0tlal4i0v62pxS53OtCApvI2W77
          rW9c+coVFcOS5jwVsL+p/jvM3j4l31Do+pMlzypqzQVTUuBSgkfIOHr+QCpjhqRmf7py2
          QXmrdhovNLkUKFf0yELPRgktZ1X84WQtspwIfcyPnY7jVP7L21QxxT0GW7ip7n19avRHt
          JGv9WxbzifY/27eW9Qgj0SZd8FveaPGomgsg7exGL+O0uCrr1Fj5iEbddWbAYg=

- job:
    name: publish-tox-docs
    parent: tox-docs
    secrets:
      - name: sftp_creds
        secret: osfrickler_docs_creds
    post-run: playbooks/publish-docs.yaml

- project:
    merge-mode: squash-merge
    vars:
      sphinx_source_dir: docs/source
      sphinx_build_dir: docs/build
    check:
      jobs:
        - tox-docs
        - tox-linters
    gate:
      jobs:
        - tox-docs
        - tox-linters
    post:
      jobs:
        - publish-tox-docs
